server:
  port: 12799

jwt:
  secret: sqwsxcq3ffcasdqwd3dsa
  expiration: 86400000
  refresh-token:
    expiration: 604800000

spring:
  application:
    name: self-recorder
  r2dbc:
    url: r2dbc:h2:mem:testdb
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "s"
            client-secret: "w"
            scope: profile, email

provider:
  snowflake:
    worker-id: 0
    data-center-id: 0

oauth2:
  # redirect to frontend react app
  redirect-url: http://localhost:5173/redirect
