spring:
  application:
    name: self-recorder
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ""
            client-secret: ""
          line:
            client-id: ""
            client-secret: ""
          github:
            client-id: ""
            client-secret: ""
